# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

hinirmcpp <- function(data, nschool, nmax, nitem, ndim, ncount, niter, nburn, nthin, nprint, jump_beta, jump_theta, jump_z, pr_mean_theta, pr_sd_theta, pr_mean_z, pr_mean_gamma, pr_sd_gamma, pr_mean_mu, pr_sd_mu, prior_a, prior_b, option = TRUE, cores = 1L) {
    .Call('_nirm_hinirmcpp', PACKAGE = 'nirm', data, nschool, nmax, nitem, ndim, ncount, niter, nburn, nthin, nprint, jump_beta, jump_theta, jump_z, pr_mean_theta, pr_sd_theta, pr_mean_z, pr_mean_gamma, pr_sd_gamma, pr_mean_mu, pr_sd_mu, prior_a, prior_b, option, cores)
}

hinirmnocpp <- function(data, nschool, nmax, nitem, ndim, ncount, niter, nburn, nthin, nprint, jump_beta, jump_theta, jump_z, pr_mean_theta, pr_sd_theta, pr_mean_z, pr_mean_gamma, pr_sd_gamma, pr_mean_mu, pr_sd_mu, prior_a, prior_b, option = TRUE, cores = 1L) {
    .Call('_nirm_hinirmnocpp', PACKAGE = 'nirm', data, nschool, nmax, nitem, ndim, ncount, niter, nburn, nthin, nprint, jump_beta, jump_theta, jump_z, pr_mean_theta, pr_sd_theta, pr_mean_z, pr_mean_gamma, pr_sd_gamma, pr_mean_mu, pr_sd_mu, prior_a, prior_b, option, cores)
}

hrnirmcpp <- function(data, nschool, nmax, nitem, ndim, ncount, niter, nburn, nthin, nprint, jump_beta, jump_theta, jump_z, jump_w, pr_mean_theta, pr_sd_theta, pr_mean_gamma, pr_sd_gamma, pr_mean_mu, pr_sd_mu, prior_a, prior_b, option = TRUE, cores = 1L) {
    .Call('_nirm_hrnirmcpp', PACKAGE = 'nirm', data, nschool, nmax, nitem, ndim, ncount, niter, nburn, nthin, nprint, jump_beta, jump_theta, jump_z, jump_w, pr_mean_theta, pr_sd_theta, pr_mean_gamma, pr_sd_gamma, pr_mean_mu, pr_sd_mu, prior_a, prior_b, option, cores)
}

hrnirmnocpp <- function(data, nschool, nmax, nitem, ndim, ncount, niter, nburn, nthin, nprint, jump_beta, jump_theta, jump_z, jump_w, pr_mean_theta, pr_sd_theta, pr_mean_gamma, pr_sd_gamma, pr_mean_mu, pr_sd_mu, prior_a, prior_b, option = TRUE, cores = 1L) {
    .Call('_nirm_hrnirmnocpp', PACKAGE = 'nirm', data, nschool, nmax, nitem, ndim, ncount, niter, nburn, nthin, nprint, jump_beta, jump_theta, jump_z, jump_w, pr_mean_theta, pr_sd_theta, pr_mean_gamma, pr_sd_gamma, pr_mean_mu, pr_sd_mu, prior_a, prior_b, option, cores)
}

hrnirmecpp <- function(data, nschool, nmax, nitem, ndim, ncount, niter, nburn, nthin, nprint, jump_beta, jump_theta, jump_w, pr_mean_theta, pr_sd_theta, pr_mean_gamma, pr_sd_gamma, pr_mean_mu, pr_sd_mu, prior_a, prior_b, option = TRUE, cores = 1L) {
    .Call('_nirm_hrnirmecpp', PACKAGE = 'nirm', data, nschool, nmax, nitem, ndim, ncount, niter, nburn, nthin, nprint, jump_beta, jump_theta, jump_w, pr_mean_theta, pr_sd_theta, pr_mean_gamma, pr_sd_gamma, pr_mean_mu, pr_sd_mu, prior_a, prior_b, option, cores)
}

hrnirmenocpp <- function(data, nschool, nmax, nitem, ndim, ncount, niter, nburn, nthin, nprint, jump_beta, jump_theta, jump_w, pr_mean_theta, pr_sd_theta, pr_mean_gamma, pr_sd_gamma, pr_mean_mu, pr_sd_mu, prior_a, prior_b, option = TRUE, cores = 1L) {
    .Call('_nirm_hrnirmenocpp', PACKAGE = 'nirm', data, nschool, nmax, nitem, ndim, ncount, niter, nburn, nthin, nprint, jump_beta, jump_theta, jump_w, pr_mean_theta, pr_sd_theta, pr_mean_gamma, pr_sd_gamma, pr_mean_mu, pr_sd_mu, prior_a, prior_b, option, cores)
}

hrnirmfcpp <- function(data, nschool, nmax, nitem, ndim, ncount, niter, nburn, nthin, nprint, jump_beta, jump_theta, jump_z, jump_w, pr_mean_theta, pr_sd_theta, pr_mean_gamma, pr_sd_gamma, pr_mean_mu, pr_sd_mu, prior_a, prior_b, fix_error, option = TRUE, cores = 1L) {
    .Call('_nirm_hrnirmfcpp', PACKAGE = 'nirm', data, nschool, nmax, nitem, ndim, ncount, niter, nburn, nthin, nprint, jump_beta, jump_theta, jump_z, jump_w, pr_mean_theta, pr_sd_theta, pr_mean_gamma, pr_sd_gamma, pr_mean_mu, pr_sd_mu, prior_a, prior_b, fix_error, option, cores)
}

inirmecpp <- function(data, nsample, nitem, ndim, niter, nburn, nthin, nprint, jump_beta, jump_theta, jump_z, pr_mean_beta, pr_sd_beta, pr_mean_theta, pr_sd_theta, pr_mean_z, prior_a, prior_b, option = TRUE, cores = 1L) {
    .Call('_nirm_inirmecpp', PACKAGE = 'nirm', data, nsample, nitem, ndim, niter, nburn, nthin, nprint, jump_beta, jump_theta, jump_z, pr_mean_beta, pr_sd_beta, pr_mean_theta, pr_sd_theta, pr_mean_z, prior_a, prior_b, option, cores)
}

inirmfcpp <- function(data, nsample, nitem, ndim, niter, nburn, nthin, nprint, jump_beta, jump_theta, jump_z, jump_w, pr_mean_beta, pr_sd_beta, pr_mean_theta, pr_sd_theta, pr_mean_z, prior_a, prior_b, fix_error, option = TRUE, cores = 1L) {
    .Call('_nirm_inirmfcpp', PACKAGE = 'nirm', data, nsample, nitem, ndim, niter, nburn, nthin, nprint, jump_beta, jump_theta, jump_z, jump_w, pr_mean_beta, pr_sd_beta, pr_mean_theta, pr_sd_theta, pr_mean_z, prior_a, prior_b, fix_error, option, cores)
}

inirmvcpp <- function(data, nsample, nitem, ndim, niter, nburn, nthin, nprint, jump_beta, jump_theta, jump_z, jump_w, pr_mean_beta, pr_sd_beta, pr_mean_theta, pr_sd_theta, pr_mean_z, prior_a, prior_b, option = TRUE, cores = 1L) {
    .Call('_nirm_inirmvcpp', PACKAGE = 'nirm', data, nsample, nitem, ndim, niter, nburn, nthin, nprint, jump_beta, jump_theta, jump_z, jump_w, pr_mean_beta, pr_sd_beta, pr_mean_theta, pr_sd_theta, pr_mean_z, prior_a, prior_b, option, cores)
}

nirmmscpp <- function(data, nsample, nitem, ndim, nset, nsamp_max, nitem_max, ntotal_max, niter, nburn, nthin, nprint, jump_beta, jump_theta, jump_z, pr_mean_beta, pr_sd_beta, pr_mean_theta, pr_sd_theta, pr_mean_z, prior_a, prior_b, option = TRUE, cores = 1L) {
    .Call('_nirm_nirmmscpp', PACKAGE = 'nirm', data, nsample, nitem, ndim, nset, nsamp_max, nitem_max, ntotal_max, niter, nburn, nthin, nprint, jump_beta, jump_theta, jump_z, pr_mean_beta, pr_sd_beta, pr_mean_theta, pr_sd_theta, pr_mean_z, prior_a, prior_b, option, cores)
}

rnirmecpp <- function(data, nsample, nitem, ndim, niter, nburn, nthin, nprint, jump_beta, jump_theta, jump_w, pr_mean_beta, pr_sd_beta, pr_mean_theta, pr_sd_theta, pr_mean_w, prior_a, prior_b, option = TRUE, cores = 1L) {
    .Call('_nirm_rnirmecpp', PACKAGE = 'nirm', data, nsample, nitem, ndim, niter, nburn, nthin, nprint, jump_beta, jump_theta, jump_w, pr_mean_beta, pr_sd_beta, pr_mean_theta, pr_sd_theta, pr_mean_w, prior_a, prior_b, option, cores)
}

rnirmfcpp <- function(data, nsample, nitem, ndim, niter, nburn, nthin, nprint, jump_beta, jump_theta, jump_z, jump_w, pr_mean_beta, pr_sd_beta, pr_mean_theta, pr_sd_theta, pr_mean_w, prior_a, prior_b, fix_error, option = TRUE, cores = 1L) {
    .Call('_nirm_rnirmfcpp', PACKAGE = 'nirm', data, nsample, nitem, ndim, niter, nburn, nthin, nprint, jump_beta, jump_theta, jump_z, jump_w, pr_mean_beta, pr_sd_beta, pr_mean_theta, pr_sd_theta, pr_mean_w, prior_a, prior_b, fix_error, option, cores)
}

rnirmvcpp <- function(data, nsample, nitem, ndim, niter, nburn, nthin, nprint, jump_beta, jump_theta, jump_z, jump_w, pr_mean_beta, pr_sd_beta, pr_mean_theta, pr_sd_theta, pr_mean_w, prior_a, prior_b, option = TRUE, cores = 1L) {
    .Call('_nirm_rnirmvcpp', PACKAGE = 'nirm', data, nsample, nitem, ndim, niter, nburn, nthin, nprint, jump_beta, jump_theta, jump_z, jump_w, pr_mean_beta, pr_sd_beta, pr_mean_theta, pr_sd_theta, pr_mean_w, prior_a, prior_b, option, cores)
}

